# Generated by Django 5.1.2 on 2024-10-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Title of Blog')),
                ('content', models.TextField(max_length=5000, verbose_name='Content of Blog')),
                ('date', models.DateField(auto_now=True, verbose_name='Blog Publication Date')),
                ('author', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='Author of Blog')),
            ],
        ),
    ]
