# Generated by Django 5.1.2 on 2024-10-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.BigAutoField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=300, unique=True, verbose_name='Author of Blog'),
        ),
    ]
