# Generated by Django 5.1.2 on 2024-10-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0006_alter_post_author_alter_post_content_alter_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_content',
            field=models.TextField(default=True, max_length=5000),
        ),
    ]
