# Generated by Django 5.1.2 on 2024-10-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0007_post_title_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='Travel'),
        ),
    ]
